[workspace]
name = "mrover"
version = "2025.0.0"
channels = ["robostack-jazzy", "conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = "3.12.*"

# ROS 2 Humble via RoboStack.
ros-jazzy-ros-base = "*"
ros-jazzy-xacro = "*"
ros-jazzy-rtcm-msgs = "*"
ros-jazzy-dynamixel-sdk = "*"
ros-jazzy-tf-transformations = "*"
ros-jazzy-ament-cmake = "*"
ros-jazzy-ament-cmake-python = "*"
ros-jazzy-rosidl-default-generators = "*"
ros-jazzy-rosidl-default-runtime = "*"

cmake = "*"
ninja = "*"
pkg-config = "*"
c-compiler = "*"
cxx-compiler = "*"
ccache = "*"
colcon-common-extensions = "==0.3.0"

magic_enum = "*"        # not in robostack-HUMBLE; use conda-forge
numpy = ">=2.0"
libboost-devel = "1.88.*"

eigen = "*"
opencv = "*"
manif = "*"
manifpy = ">=0.0.5,<0.0.6"
glfw = "*"
assimp = "*"
bullet = "*"
qt-main = "*"
gstreamer = "*"
gst-plugins-base = "*"
bun = "*"
ros-jazzy-rviz2 = ">=14.1.19,<15"

[target.linux-64.dependencies]
tbb = "*"
tbb-devel = "*"

[pypi-dependencies]
mrover = { path = ".", editable = true }

[feature.dev.dependencies]
black = "*"
mypy = "*"
ipython = "*"
pytest = "*"
pytest-asyncio = "*"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
