# CAN messaging
can_id: 54
host_can_id: 16

# system configuration
motor_en: true
motor_inv: true
quad_en: false
quad_phase: false

# limit configuration
lim_a_en: false
lim_a_active_high: false
lim_a_is_forward: false
lim_a_use_readjust: true
lim_b_en: false
lim_b_active_high: false
lim_b_is_forward: false
lim_b_use_readjust: false

# encoder params
quad_cpr: 1.0 # no quad encoder
gear_ratio: 1.0 # no quad encoder
rotor_output_ratio: 1.0 # no quad encoder

# position & velocity limits
limit_a_position: 0.0
limit_b_position: 0.04
max_pwm: 1.0
min_pos: 0.0
max_pos: 0.04
min_vel: -0.1
max_vel: 0.1

# control gains
pos_k_p: 0.0
pos_k_i: 0.0
pos_k_d: 0.0
pos_k_f: 0.0
vel_k_p: 0.0
vel_k_i: 0.0
vel_k_d: 0.0
vel_k_f: 0.0
