- name: Add GitHub CLI dnf repo
  become: true
  ansible.builtin.yum_repository:
    name: gh-cli
    description: GitHub CLI
    baseurl: https://cli.github.com/packages/rpm
    gpgkey: https://cli.github.com/packages/githubcli-archive-keyring.asc
    gpgcheck: true
    enabled: true

- name: Add VSCode dnf repo
  become: true
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true
    enabled: true

- name: Install dnf packages
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - zsh
      - fzf
      - tmux
      - htop
      - gh
      - code
      - git-lfs
      - chromium
