- name: Add GitHub CLI dnf repo
  become: true
  ansible.builtin.command: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
  args:
    creates: /etc/yum.repos.d/gh-cli.repo

- name: Import VSCode RPM key
  become: true
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VSCode dnf repo
  become: true
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/vscode.repo
    content: |
      [code]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc

- name: Install dnf packages
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - zsh
      - fzf
      - tmux
      - htop
      - gh
      - code
      - git-lfs
      - chromium
