- name: Install brew packages
  community.general.homebrew:
    name:
      - fzf
      - tmux
      - htop
      - gh
      - git-lfs
      - pixi
      - bun
      - llvm
    state: present

- name: Check if VSCode is already installed
  ansible.builtin.stat:
    path: /Applications/Visual Studio Code.app
  register: vscode_app

- name: Check if Google Chrome is already installed
  ansible.builtin.stat:
    path: /Applications/Google Chrome.app
  register: chrome_app

- name: Install VSCode cask
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
  when: not vscode_app.stat.exists

- name: Install Google Chrome cask
  community.general.homebrew_cask:
    name: google-chrome
    state: present
  when: not chrome_app.stat.exists
