- name: Install brew packages
  community.general.homebrew:
    name:
      - fzf
      - tmux
      - htop
      - gh
    state: present

- name: Install VSCode and Chromium casks
  community.general.homebrew_cask:
    name:
      - visual-studio-code
      - chromium
    state: present
