- name: Install platform-specific packages
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: Install oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    version: master

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

# theme is deployed regardless
- name: Deploy mrover oh-my-zsh theme
  ansible.builtin.copy:
    src: files/home/.oh-my-zsh/custom/themes/mrover.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/mrover.zsh-theme

- name: Check for existing zshrc
  ansible.builtin.stat:
    path: ~/.zshrc
  register: zshrc_stat

# if user does not have zshrc, deploy ours
- name: Deploy default oh-my-zsh zshrc for fresh installs
  ansible.builtin.copy:
    src: files/home/.zshrc
    dest: ~/.zshrc
  when: not zshrc_stat.stat.exists

# mrover_zshenv handled by flag via defaults
- name: Wire mrover shell env
  ansible.builtin.blockinfile:
    path: ~/.zshrc
    marker: "# {mark} MROVER"
    block: '[[ -f "${MROVER_REPO:-$HOME/mrover-ros2}/{{ mrover_zshenv }}" ]] && source "${MROVER_REPO:-$HOME/mrover-ros2}/{{ mrover_zshenv }}"'
    create: true

- name: Deploy mrover tmux config
  ansible.builtin.copy:
    src: files/home/.mrover.tmux.conf
    dest: ~/.mrover.tmux.conf

- name: Source mrover tmux config
  ansible.builtin.blockinfile:
    path: ~/.tmux.conf
    marker: "# {mark} MROVER"
    block: source-file ~/.mrover.tmux.conf
    create: true

# this is needed because linux distros install zsh at /usr/bin/zsh, but macos places the zsh binary at /bin/zsh
- name: Resolve zsh binary path
  ansible.builtin.command: which zsh
  register: zsh_path
  changed_when: false

- name: Set zsh as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: "{{ zsh_path.stdout }}"

- name: Initialize Git LFS
  # use git lfs pre-push hook for ansible changed
  ansible.builtin.command: git lfs install
  args:
    chdir: "{{ mrover_repo }}"
    creates: "{{ mrover_repo }}/.git/hooks/pre-push"

- name: Pull Git LFS objects
  ansible.builtin.command: git lfs pull
  args:
    chdir: "{{ mrover_repo }}"
  changed_when: false

- name: Initialize Git submodules
  ansible.builtin.command: git submodule update --init --recursive
  args:
    chdir: "{{ mrover_repo }}"
  register: git_submodules
  changed_when: git_submodules.stdout | length > 0

- name: Look for VSCode
  ansible.builtin.shell: command -v code
  register: vscode_path
  changed_when: false
  failed_when: false
  check_mode: false

- name: List installed VSCode extensions
  ansible.builtin.command: code --list-extensions
  register: vscode_extensions
  changed_when: false
  check_mode: false
  when: vscode_path.rc == 0

- name: Install VSCode extension
  ansible.builtin.command: code --install-extension {{ mrover_repo }}/pkg/file-selector-0.0.1.vsix
  when:
    - vscode_path.rc == 0
    - "'file-selector' not in vscode_extensions.stdout"
