- name: Install platform-specific packages
  include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: Install oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    version: master

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Deploy mrover oh-my-zsh theme
  copy:
    src: files/home/.oh-my-zsh/custom/themes/mrover.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/mrover.zsh-theme

- name: Deploy mrover config
  copy:
    src: files/home/.mrover.zshenv
    dest: ~/.mrover.zshenv

- name: Source mrover config
  blockinfile:
    path: ~/.zshenv
    marker: "# {mark} MROVER"
    block: source ~/.mrover.zshenv
    create: true

- name: Deploy mrover tmux config
  copy:
    src: files/home/.mrover.tmux.conf
    dest: ~/.mrover.tmux.conf

- name: Source mrover tmux config
  blockinfile:
    path: ~/.tmux.conf
    marker: "# {mark} MROVER"
    block: source-file ~/.mrover.tmux.conf
    create: true

- name: Set zsh as default shell
  become: true
  command: chsh -s "$(which zsh)" "{{ ansible_user_id }}"
  changed_when: false

- name: Install VSCode extension
  command: code --install-extension ../pkg/file-selector-0.0.1.vsix
