# CAN messaging
can_id: 103
host_can_id: 16

# system configuration
motor_en: true
motor_inv: false
quad_en: true
quad_phase: false

# limit configuration
lim_a_en: true
lim_a_active_high: false
lim_a_is_forward: true
lim_a_use_readjust: true
lim_b_en: true
lim_b_active_high: false
lim_b_is_forward: false
lim_b_use_readjust: true

# encoder params
quad_cpr: 48.0
gear_ratio: 47.0  # :1
rotor_output_ratio: 1.0 # revolutions:revolutions

# position & velocity limits
limit_a_position: 0.0
limit_b_position: 100.0
max_pwm: 1.0
min_pos: 0.0
max_pos: 100.0
min_vel: -3.3
max_vel: 3.3

# control gains
pos_k_p: 5.0
pos_k_i: 1.0
pos_k_d: 1.0
pos_k_f: 0.0
vel_k_p: 0.4
vel_k_i: 0.1
vel_k_d: 0.1
vel_k_f: 0.2
