- name: Extract PCAN drivers
  become: true
  unarchive:
    src: files/peak-linux-driver-8.20.0.tar.gz
    dest: /tmp/
    remote_src: no

- name: Make PCAN drivers
  become: true
  make:
    chdir: /tmp/peak-linux-driver-8.20.0
    target: netdev

- name: Install PCAN drivers
  become: true
  make:
    chdir: /tmp/peak-linux-driver-8.20.0
    target: install

- name: Install CAN restart script
  become: true
  copy:
    src: files/restart_can
    dest: /usr/local/bin/
    mode: 0775

- name: Copy CAN service file
  become: true
  ansible.builtin.copy:
    src: files/can.service
    dest: /etc/systemd/system/can.service
    mode: 0644

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable CAN service
  ansible.builtin.systemd:
    name: can.service
    enabled: yes

- name: Start CAN service
  ansible.builtin.systemd:
    name: can.service
    state: started
