antenna_bridge:
  ros__parameters:
    antenna:
      gear_ratio: 1.0
      is_inverted: false
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      quad_present: true
      quad_ratio: 0.0625
      abs_present: false

can_bridge_antenna:
  ros__parameters:
    interface: can4
    is_extended_frame: true
    devices:
      rpi:
        id: 0x05
      antenna:
        id: 0x0A
