/**:
  ros__parameters:
    ee1_cam:
      address: 10.1.0.2
      port: 8087
      dev_node: "/dev/port_a1_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 5
    ee2_cam:
      address: 10.1.0.2
      port: 8088
      dev_node: "/dev/port_a2_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 5
    ee3_cam:
      address: 10.1.0.2
      port: 8089
      dev_node: "/dev/port_a3_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 5
    sp1_cam:
      address: 10.1.0.2
      port: 8090
      dev_node: "/dev/port_a1_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 5
    sp2_cam:
      address: 10.1.0.2
      port: 8091
      dev_node: "/dev/port_a2_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 5
    ee4_cam:
      address: 10.1.0.2
      port: 8092
      dev_node: "/dev/port_b1_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 5
    ee5_cam:
      address: 10.1.0.2
      port: 8093
      dev_node: "/dev/port_b2_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 5
    mob_left_cam:
      address: 10.1.0.2
      port: 8094
      dev_node: "/dev/port_c1_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 5
    gps_left_cam:
      address: 10.1.0.2
      port: 8095
      dev_node: "/dev/port_c2_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 5
    mob_right_cam:
      address: 10.1.0.2
      port: 8096
      dev_node: "/dev/port_d1_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 5
    gps_right_cam:
      address: 10.1.0.2
      port: 8097
      dev_node: "/dev/port_d2_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 5
    zed_mini:
      address: 10.1.0.2
      port: 8082
      image_topic: "/zed_mini/left/image"
      stream:
        pixel_format: ABGR32 # https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/pixfmt-packed-rgb.html
        width: 1280
        height: 720
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: ABGR32
        width: 1280
        height: 720
        framerate: 15
    zed:
      address: 10.1.0.2
      port: 8083
      image_topic: "/zed/left/image"
      stream:
        pixel_format: ABGR32 # https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/pixfmt-packed-rgb.html
        width: 1280
        height: 720
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: ABGR32
        width: 1280
        height: 720
        framerate: 15
    long_range_cam:
      address: 10.1.0.2
      port: 8084
      image_topic: "/long_range_cam/image"
      stream:
        pixel_format: ABGR32 # https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/pixfmt-packed-rgb.html
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: ABGR32
        width: 640
        height: 480
        framerate: 15
    long_range_cam_annotated:
      address: 10.1.0.2
      port: 8085
      image_topic: "/long_range_object_detector/annotated_img"
      stream:
        pixel_format: ABGR32 # https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/pixfmt-packed-rgb.html
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: ABGR32
        width: 640
        height: 480
        framerate: 15
    zed_annotated:
      address: 10.1.0.2
      port: 8086
      image_topic: "/stereo_object_detector/annotated_img"
      stream:
        pixel_format: ABGR32 # https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/pixfmt-packed-rgb.html
        width: 1280
        height: 720
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: ABGR32
        width: 1280
        height: 720
        framerate: 15

ee1_streamer:
  ros__parameters:
    camera: "ee1_cam"

ee2_streamer:
  ros__parameters:
    camera: "ee2_cam"

ee3_streamer:
  ros__parameters:
    camera: "ee3_cam"

sp1_streamer:
  ros__parameters:
    camera: "sp1_cam"

sp2_streamer:
  ros__parameters:
    camera: "sp2_cam"

ee4_streamer:
  ros__parameters:
    camera: "ee4_cam"

ee5_streamer:
  ros__parameters:
    camera: "ee5_cam"

mob_left_streamer:
  ros__parameters:
    camera: "mob_left_cam"

mob_right_streamer:
  ros__parameters:
    camera: "mob_right_cam"

gps_left_streamer:
  ros__parameters:
    camera: "gps_left_cam"

gps_right_streamer:
  ros__parameters:
    camera: "gps_right_cam"

zed_mini_streamer:
  ros__parameters:
    camera: "zed_mini"

zed_streamer:
  ros__parameters:
    camera: "zed"

long_range_streamer:
  ros__parameters:
    camera: "long_range_cam"

zed_streamer_annotated:
  ros__parameters:
    camera: "zed_annotated"

long_range_streamer_annotated:
  ros__parameters:
    camera: "long_range_cam_annotated"

camera_client:
  ros__parameters:
    test: 10
    arm:
      cameras:
        # main
        - "ee1_cam_main"
        - "ee2_cam_main"
        - "ee3_cam_main"
        - "ee4_cam_main"
        - "ee5_cam_main"
        - "zed_main"

        # secondary
        - "mob_left_cam_second"
        - "mob_right_cam_second"
        - "gps_left_cam_second"
        - "gps_right_cam_second"
        - "zed_mini_second"
    science:
      cameras:
        # main
        - "sp1_cam_main"
        - "sp2_cam_main"
        - "zed_main"

        # second
        - "mob_left_cam_second"
        - "mob_right_cam_second"
        - "gps_left_cam_second"
        - "gps_right_cam_second"
        - "zed_mini_second"
    auton:
      cameras:
        # main
        - "zed_annotated_main"
        - "long_range_cam_annotated_main"

        # second
        - "mob_left_cam_second"
        - "mob_right_cam_second"
        - "gps_left_cam_second"
        - "gps_right_cam_second"
        - "zed_mini_second"
    rtp_jitter_ms: 50

