/**:
  ros__parameters:
    ee1_cam:
      address: 10.1.0.2
      port: 8082
      dev_node: "/dev/port_a1_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 1280
        height: 720
        framerate: 5
    ee2_cam:
      address: 10.1.0.2
      port: 8083
      dev_node: "/dev/port_a2_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 1280
        height: 720
        framerate: 5
    ee3_cam:
      address: 10.1.0.2
      port: 8084
      dev_node: "/dev/port_a3_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 1280
        height: 720
        framerate: 5
    sp1_cam:
      address: 10.1.0.2
      port: 8085
      dev_node: "/dev/port_a1_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 1280
        height: 720
        framerate: 5
    sp2_cam:
      address: 10.1.0.2
      port: 8086
      dev_node: "/dev/port_a2_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 1280
        height: 720
        framerate: 5
    joint_a_cam:
      address: 10.1.0.2
      port: 8087
      dev_node: "/dev/port_b_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 1280
        height: 720
        framerate: 5
    mob_cam:
      address: 10.1.0.2
      port: 8088
      dev_node: "/dev/port_j_cam"
      dev_path: ""
      stream:
        pixel_format: MJPG # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 1280
        height: 720
        framerate: 5
    zed_mini:
      address: 10.1.0.2
      port: 8089
      image_topic: "/zed_mini/left/image"
      stream:
        pixel_format: ABGR32 # https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/pixfmt-packed-rgb.html
        width: 1280
        height: 720
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: ABGR32
        width: 1280
        height: 720
        framerate: 15
    zed:
      address: 10.1.0.2
      port: 8090
      image_topic: "/zed/left/image"
      stream:
        pixel_format: ABGR32 # https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/pixfmt-packed-rgb.html
        width: 1280
        height: 720
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: ABGR32
        width: 1280
        height: 720
        framerate: 15
    long_range_cam:
      address: 10.1.0.2
      port: 8091
      image_topic: "/long_range_cam/image"
      stream:
        pixel_format: ABGR32 # https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/pixfmt-packed-rgb.html
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: ABGR32
        width: 640
        height: 480
        framerate: 15

ee1_streamer:
  ros__parameters:
    camera: "ee1_cam"

ee2_streamer:
  ros__parameters:
    camera: "ee2_cam"

ee3_streamer:
  ros__parameters:
    camera: "ee3_cam"

sp1_streamer:
  ros__parameters:
    camera: "sp1_cam"

sp2_streamer:
  ros__parameters:
    camera: "sp2_cam"

joint_a_streamer:
  ros__parameters:
    camera: "joint_a_cam"

mob_streamer:
  ros__parameters:
    camera: "mob_cam"

zed_mini_streamer:
  ros__parameters:
    camera: "zed_mini"

zed_streamer:
  ros__parameters:
    camera: "zed"

long_range_streamer:
  ros__parameters:
    camera: "long_range_cam"

camera_client:
  ros__parameters:
    test: 10
    arm:
      cameras:
        - "mob_cam"
        - "joint_a_cam"
        - "ee1_cam"
        - "ee2_cam"
        - "ee3_cam"
        - "zed_mini"
        - "zed"
    science:
      cameras:
        - "sp1_cam"
        - "sp2_cam"
        - "mob_cam"
        - "zed_mini"
        - "zed"
    auton:
      cameras:
        - "mob_cam"
        - "zed_mini"
        - "zed"
        - "long_range_cam"
    rtp_jitter_ms: 50

