mast_gimbal_hw_bridge:
  ros__parameters:
    u2d2_device: "/dev/u2d2"
    gimbal_pitch:
      id: 3
      position_multiplier: 1.0
      forward_limit: 110.0
      reverse_limit: 350.0
      position_p: 5000.0
      position_i: 0.0
      position_d: 0.0
      velocity_p: 0.0
      velocity_i: 0.0
      current_limit: 1750.0
      profile_acceleration: 10.0
      profile_velocity: 60.0
    gimbal_yaw:
      id: 4
      position_multiplier: 6.25
      forward_limit: 350.0
      reverse_limit: 10.0
      position_p: 4000.0
      position_i: 0.0
      position_d: 0.0
      velocity_p: 0.0
      velocity_i: 0.0
      current_limit: 1000.0
      profile_acceleration: 100.0
      profile_velocity: 300.0
