# All units are in SI
# ===================
# Time:     second, hz
# Angle:    radian
# Distance: meter

objects:
  rover:
    uri: mjcf/rover.xml
    position: [ 0.0, 0.0, 0.5 ]
  tag_0:
    uri: mjcf/tag_0.xml
    fixed: true
    position: [ 11.0, 3.0, 0.7 ]
  tag_1:
    uri: mjcf/tag_1.xml
    fixed: true
    position: [ 15.0, -14.0, 2.4 ]
  mallet:
    uri: mjcf/hammer.xml
    position: [ -2.0, -2.0, 0.7 ]
  bottle:
    uri: mjcf/bottle.xml
    position: [ -6.25, 10.5, 0.3 ]
  rock1:
    uri: mjcf/rock.xml
    fixed: true
    position: [ 2.0, -2.0, 0.1 ]
  rock2:
    uri: mjcf/rock.xml
    fixed: true
    position: [ 7.0, -6.0, 0.2 ]
  rock3:
    uri: mjcf/rock.xml
    fixed: true
    position: [ 8.0, -10.0, 1.0 ]
  rock4:
    uri: mjcf/rock.xml
    fixed: true
    position: [ 9.0, -2.0, 0.2 ]
