# All units are in SI
# ===================
# Time:     second, hz
# Angle:    radian
# Distance: meter

objects:
  rover:
    uri: mjcf/rover.xml
    position: [ 0.0, 0.0, 0.5 ]
  lander:
    uri: mjcf/lander.xml
    fixed: true
    position: [ 1.0, 1.0, 0.1 ]
