# Generated by Django 5.1.1 on 2025-01-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_joystick_delete_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonWaypoint",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ("tag_id", models.IntegerField()),
                ("type", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BasicWaypoint",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, unique=True)),
                ("drone", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Joystick",
        ),
    ]
