# Generated by Django 5.1.1 on 2025-01-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_autonwaypoint_basicwaypoint_delete_joystick"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autonwaypoint",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
