# Generated by Django 5.2.3 on 2025-07-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_alter_autonwaypoint_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentAutonWaypoints",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, unique=True)),
                ("tag_id", models.IntegerField()),
                ("type", models.IntegerField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("name", models.CharField(max_length=100)),
                ("enable_costmap", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CurrentBasicWaypoints",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, unique=True)),
                ("drone", models.BooleanField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
