# Generated by Django 5.2.6 on 2025-10-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_currentautonwaypoints_currentbasicwaypoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="autonwaypoint",
            name="enable_costmap",
            field=models.BooleanField(default=True),
        ),
    ]
