# Generated by Django 5.2.11 on 2026-02-05 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_autonwaypoint_enable_costmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autonwaypoint',
            name='enable_costmap',
        ),
    ]
