# Generated by Django 5.2.6 on 2025-11-04 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_autonwaypoint_enable_costmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaypointRecording",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_drone", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecordedWaypoint",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("sequence", models.IntegerField()),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="backend.waypointrecording",
                    ),
                ),
            ],
        ),
    ]
