- name: USB Rules
  become: true
  ansible.builtin.copy:
    src: files/rules/
    dest: /etc/udev/rules.d

- name: udev Reload Rules
  become: true
  ansible.builtin.command: udevadm control --reload-rules

- name: udev TTY Trigger
  become: true
  ansible.builtin.command: udevadm trigger --subsystem-match=tty
