- name: Jetson Flash
  block:
  - name: Create Jetson Flash Directory
    file:
      path: "{{ jetson_flash_dir }}"
      state: directory

  - name: Create Downloads Directory
    file:
      path: "{{ jetson_flash_dir }}/downloads"
      state: directory

  - name: Get Jetson Drivers
    get_url:
      url: https://developer.nvidia.com/downloads/embedded/l4t/r{{ jetson_linux_version_major }}_release_v{{ jetson_linux_version_minor }}.{{ jetson_linux_version_patch }}/release/Jetson_Linux_r{{ jetson_linux_version_major }}.{{ jetson_linux_version_minor }}.{{ jetson_linux_version_patch }}_aarch64.tbz2
      dest: "{{ jetson_flash_dir }}/downloads/jetson-driver-package.tbz2"

  - name: Get Jetson Root File System
    get_url:
      url: https://developer.nvidia.com/downloads/embedded/l4t/r{{ jetson_linux_version_major }}_release_v{{ jetson_linux_version_minor }}.{{ jetson_linux_version_patch }}/release/Tegra_Linux_Sample-Root-Filesystem_r{{ jetson_linux_version_major }}.{{ jetson_linux_version_minor }}.{{ jetson_linux_version_patch }}_aarch64.tbz2
      dest: "{{ jetson_flash_dir }}/downloads/jetson-rootfs-package.tbz2"

  - name: Get Jetson Cross Compiler
    get_url:
      url: "{{ x_tools_url }}"
      dest: "{{ jetson_flash_dir }}/downloads/jetson-cross-compiler.tbz2"

  - name: Get PCAN Drivers
    get_url:
      url: https://www.peak-system.com/fileadmin/media/linux/files/peak-linux-driver-{{ pcan_version_major }}.{{ pcan_version_minor }}.{{ pcan_version_patch }}.tar.gz
      dest: "{{ jetson_flash_dir }}/downloads/pcan-drivers.tar.gz"

  - name: Unzip Driver Tarball
    unarchive:
      src: "{{ jetson_flash_dir }}/downloads/jetson-driver-package.tbz2"
      dest: "{{ jetson_flash_dir }}"
      creates: "{{ jetson_flash_dir }}/Linux_for_Tegra/bootloader"

  - name: Unzip RootFs Tarball
    become: true
    unarchive:
      src: "{{ jetson_flash_dir }}/downloads/jetson-rootfs-package.tbz2"
      dest: "{{ jetson_flash_dir }}/Linux_for_Tegra/rootfs/"
      creates: "{{ jetson_flash_dir }}/Linux_for_Tegra/rootfs/bin"

  - name: Unzip Cross Compiler
    unarchive:
      src: "{{ jetson_flash_dir }}/downloads/jetson-cross-compiler.tbz2"
      dest: "{{ jetson_flash_dir }}"
      creates: "{{ jetson_flash_dir }}/x-tools/aarch64*"

  - name: Unzip PCAN Drivers
    unarchive:
      src: "{{ jetson_flash_dir }}/downloads/pcan-drivers.tar.gz"
      dest: "{{ jetson_flash_dir }}"
      creates: "{{ jetson_flash_dir }}/peak-linux-driver-{{ pcan_version_major }}.{{ pcan_version_minor }}.{{ pcan_version_patch }}"

  - name: Remove PCAN Testing
    # TODO(john): this is not the best solution
    replace:
      path: "{{ jetson_flash_dir }}/peak-linux-driver-{{ pcan_version_major }}.{{ pcan_version_minor }}.{{ pcan_version_patch }}/Makefile"
      regexp: "\\@\\$\\(MAKE\\) -C test \\$1"
      replace: ""

  - name: Run L4T Flash Prerequisites
    become: true
    shell:
      chdir: "{{ jetson_flash_dir }}/Linux_for_Tegra"
      cmd: ./tools/l4t_flash_prerequisites.sh

  - name: Run Apply Binaries
    become: true
    shell:
      chdir: "{{ jetson_flash_dir }}/Linux_for_Tegra"
      cmd: ./apply_binaries.sh

  - name: Install Apt Packages
    become: true
    apt:
      cache_valid_time: 604800
      state: latest
      name:
        - git
        - build-essential
        - bc
        - flex
        - bison
        - libssl-dev
        - zstd

  - name: Sync Kernel Sources
    shell:
      chdir: "{{ jetson_flash_dir }}/Linux_for_Tegra/source"
      cmd: ./source_sync.sh -k -t jetson_{{ jetson_linux_version_major }}.{{ jetson_linux_version_minor }}.{{ jetson_linux_version_patch }}
      creates: "{{ jetson_flash_dir }}/Linux_for_Tegra/source/kernel/kernel-{{ ubuntu_codename }}-src"
  #
  # - name: Sync Kernel Configuration
  #   synchronize:
  #     src: files/config
  #     dest: "{{ jetson_flash_dir }}/jetson-flash/Linux_for_Tegra/source/kernel/kernel-{{ ubuntu_codename }}-src/.config"
  #
  # - name: Sync Kernel Configuration With Oldconfig
  #   synchronize:
  #     src: files/config
  #     dest: "{{ jetson_flash_dir }}/jetson-flash/Linux_for_Tegra/source/kernel/kernel-{{ ubuntu_codename }}-src/arch/arm64/configs/oldconfig"
  #
  # - name: Build Jetson Kernel
  #   become: true
  #   command: ./ansible/roles/jetson_flash/files/scripts/build_jetson_kernel.sh
  #   failed_when: False # this is not ideal
  #   args:
  #     chdir: "{{ mrover_repo }}"
  #     # no creates here because it is always desired to recompile the kernel if running this ansible
  #
  # - name: Build PCAN
  #   become: true
  #   command: ./ansible/roles/jetson_flash/files/scripts/build_pcan_drivers.sh {{ pcan_version_major }} {{ pcan_version_minor }} {{ pcan_version_patch }}
  #   args:
  #     chdir: "{{ mrover_repo }}"
  #     # no creates here because we always rebuild
  #
  # - name: Ensure Jetson Is Connected In Recovery Mode
  #   shell:
  #     cmd: lsusb | grep "7023 NVIDIA"
  #
  # - name: Flash Jetson
  #   become: true
  #   command: ./flash.sh jetson-agx-orin-devkit internal
  #   args:
  #     chdir: "{{ jetson_flash_dir }}/jetson-flash/Linux_for_Tegra"

  vars:
    jetson_flash_dir: "/tmp/jetson_flash-{{ jetson_linux_version_major }}-{{ jetson_linux_version_minor }}-{{ jetson_linux_version_patch }}"
