# find the tool chain
find_program(CMAKE_CXX_COMPILER NAMES "clang++-18")
find_program(CMAKE_C_COMPILER NAMES "clang-18")
find_program(CMAKE_CUDA_HOST_COMPILER NAMES "g++-9")
find_program(CMAKE_CUDA_COMPILER NAMES "nvcc")
if(NOT APPLE)
    find_program(CMAKE_LINKER NAMES "lld-18")
endif()

# print status
if(NOT ${CMAKE_CXX_COMPILER})
    message(FATAL_ERROR "CMAKE_CXX_COMPILER NOT FOUND")
endif()
if(NOT ${CMAKE_C_COMPILER})
    message(FATAL_ERROR "CMAKE_C_COMPILER NOT FOUND")
endif()
if(NOT ${CMAKE_CUDA_HOST_COMPILER})
    message(STATUS "CMAKE_CUDA_HOST_COMPILER NOT FOUND")
endif()
if(NOT ${CMAKE_CUDA_COMPILER})
    message(STATUS "CMAKE_CUDA_COMPILER NOT FOUND")
endif()
if(NOT ${CMAKE_LINKER})
    message(STATUS "CMAKE_LINKER NOT FOUND")
endif()
