find_program(CMAKE_CXX_COMPILER NAMES "clang++-18")
find_program(CMAKE_C_COMPILER NAMES "clang-18")
find_program(CMAKE_CUDA_HOST_COMPILER NAMES "g++-9")
find_program(CMAKE_CUDA_COMPILER NAMES "nvcc")

message("CMAKE_CXX_COMPILER: ${CMAKE_CXX_COMPILER}")
message("CMAKE_C_COMPILER: ${CMAKE_C_COMPILER}")
message("CMAKE_CUDA_HOST_COMPILER: ${CMAKE_CUDA_HOST_COMPILER}")
message("CMAKE_CUDA_COMPILER: ${CMAKE_CUDA_COMPILER}")
