name: CI
on:
  pull_request:
    branches:
      - main
      - integration
  push:
    branches:
      - main
      - integration

jobs:
  style:
    name: Style Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          activate-environment: true
          cache: true
      - uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: bun-${{ hashFiles('teleoperation/basestation_gui/frontend/bun.lockb') }}
          restore-keys: bun-
      - name: Style Check
        run: ./style.sh

  build:
    name: Build (pixi Ubuntu 26)
    runs-on: ubuntu-26.04
    needs: style
    steps:
      - uses: actions/checkout@v6
      - name: Dawn Cache
        uses: actions/cache@v5
        with:
          path: deps/dawn-prebuilt
          key: dawn-${{ hashFiles('tools/setup_dawn.sh') }}
      - name: Compiler Cache
        uses: hendrikmuhs/ccache-action@v1.2.23
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          activate-environment: true
          cache: true
      - name: Build
        env:
          MROVER_BUILD_JOBS: 2
        run: ./build.sh

  build-native:
    name: Build (native Ubuntu 24)
    runs-on: ubuntu-24.04
    container:
      image: ${{ secrets.DOCKERHUB_USERNAME }}/mrover-ci:latest
    needs: style
    steps:
      - uses: actions/checkout@v6
      - name: Dawn Cache
        uses: actions/cache@v5
        with:
          path: deps/dawn-prebuilt
          key: dawn-${{ hashFiles('tools/setup_dawn.sh') }}
      - name: Setup Dawn
        run: ./tools/setup_dawn.sh
      - name: Compiler Cache
        uses: hendrikmuhs/ccache-action@v1.2.23
      - name: Build
        env:
          MROVER_BUILD_JOBS: 2
        run: |
          source /opt/ros/jazzy/setup.bash
          ./build_ci.sh
