name: CI
on:
  pull_request:
    branches:
      - main
      - integration
  push:
    branches:
      - main
      - integration

jobs:
  style:
    name: Style Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          environments: dev
          activate-environment: dev
          cache: true
      - name: Style Check
        run: ./style.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: style
    steps:
      - uses: actions/checkout@v6.0.3
      - name: Compiler Cache
        if: github.event.pull_request.draft == false
        uses: hendrikmuhs/ccache-action@v1.2.23
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          activate-environment: true
          cache: true
      - name: Build
        if: github.event.pull_request.draft == false
        env:
          MROVER_BUILD_JOBS: 2
        run: ./build.sh
