name: Playwright Tests
on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: umrover1/ros2:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: cd teleoperation && npm install && npx playwright install
      - name: Run tests
        run: npx playwright test tests/ui/